finally working, might need minor debugging

diff --git a/debian/folder2ram.prerm b/debian/folder2ram.prerm
--- a/debian/folder2ram.prerm
+++ b/debian/folder2ram.prerm
@@ -5,6 +5,44 @@
 
 set -e
 
-folder2ram unmount -a 
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+	#the init scripts are completely independent, so they will be fine.
+	#the config is generated when the user gives a command so it is fine too.
+	#the configuration script is run only when configuring so it is fine.
+
+case "$1" in
+    remove|deconfigure)
+
+	[ -f /sbin/folder2ram ] && folder2ram -clean
+
+	[ -f /etc/folder2ram/folder2ram.conf ] && rm -f /etc/folder2ram/folder2ram.conf
+    ;;
+
+    upgrade|failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
+
+
